# Generated by Django 5.2.6 on 2025-09-30 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('expected_return_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrowing',
                'verbose_name_plural': 'Borrowings',
                'ordering': ['-borrow_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('expected_return_date__gt', models.F('borrow_date'))), name='expected_return_date_gt_borrow_date'), models.CheckConstraint(condition=models.Q(('actual_return_date__isnull', True), ('actual_return_date__gte', models.F('borrow_date')), _connector='OR'), name='actual_return_date_gte_borrow_date_if_not_null')],
            },
        ),
    ]
